<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Setting;

/**
 * SettingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAll()
    {
        /** @var Setting[] $settings */
        $settings = $this->findAll();
        $result = [];

        foreach ($settings as $setting) {
            $result[$setting->getSlug()] = $setting->getValue();
        }

        return $result;
    }
}
