# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.command.handler.task_update:
    class: 'AppBundle\Command\TaskUpdateHandler'
    arguments:
      - '@state_machine.task_management'
      - '@doctrine.orm.default_entity_manager'
  app.form.update_task:
    class: 'AppBundle\Form\UpdateTaskType'
    arguments:
      - '@state_machine.task_management'
    tags:
      - { name: 'form.type' }
